### ISSUE TITLE
Installing Alpha Version

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce-paypal-checkout#1]
I'm trying to install via composer using the given instructions but getting this error due to the alpha version

`composer require craftcms/commerce-paypal-checkout`

```
  [InvalidArgumentException]                                                          
  Could not find a matching version of package craftcms/commerce-paypal-checkout. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable). 
```

What would be the best way to install for this version?

I also couldn't find it in the marketplace yet, but assuming that's because of the alpha version.

Thanks

**Comment by nfourtythree** [comment]
Hey @keyurshah 

Sorry, I thought this had been submitted to packagist. It is there now, and I will tag an alpha release so you can get this up and running. 

Thanks.

**Comment by keyurshah** [comment]
I'm still getting the same error. do I need to change my composer.json to allow for the alpha version?
