### ISSUE TITLE
Pass Payer details to Paypal

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/commerce-paypal-checkout#11]
It looks like PayPal Checkout supports the passing of payer details: https://developer.paypal.com/docs/api/orders/v2/#definition-payer

This would allow the passing of billing information to PayPal to have things pre-filled out.

**Comment by nfourtythree** [comment]
We have added the passing of payer details. This will be included in the next release.

**Comment by RitterKnightCreative** [comment]
This works pretty well. The only thing it's missing is passing in the US state and phone number from the order.
