### ISSUE TITLE
Orders with successful authorize transaction not marked complete

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce-paypal-checkout#13]
PayPal works when payment type is set to Purchase, but when set to Authorize Only the order is not marked complete. It takes you through the checkout process, but after completing payment on PayPal's end, the order is not marked complete. Viewing order's transactions tab shows a successful authorize transaction. My testing environment is:

- Craft 3.4.14
- PHP 7.2.24
- MySQL 5.5.5
- Commerce 3.1.1 with my pull request #12 applied

**Comment by nfourtythree** [comment]
Hi

Thank you for this.

I am looking into it along with the PR raised and something in the internals of Commerce.

Will keep you updated with how this progresses and hopefully get a fix out soon.

Thanks.

**Comment by nfourtythree** [comment]
Just another update this commit on Commerce is also related (https://github.com/craftcms/commerce/commit/1f64eb17f921d30fe75f909da239fc5e7e47f70f).

A release for Commerce is coming soon, along with this an updated release to this gateway.

**Comment by jmauzyk** [comment]
@nfourtythree Thanks for your work on this!

**Comment by nfourtythree** [comment]
Hi @jmauzyk 

This is fixed with today's release of Commerce `3.1.2`.

Thanks.
