### ISSUE TITLE
Problem with redirect URL

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce-paypal-checkout#15]
Sorry to bother you again but I have an issue with the redirect URL of this plugin.

When I try to create a purchase with this payment gateway the redirect URL from the `CheckoutResponse` is always something like "4KB071933T822801A" causing me to redirect to URLs like "https://example.dev/admin/commerce/orders/4KB071933T822801A" and those of cause throw a 400 Bad request exception.

So the `actionUrl` in my `gatewayPostRedirectTemplate` is always just `4KB071933T822801A`. Am I supposed to change this?

This time I read the Readme, am I still missing something? Where should I be redirected?

Edit: When I change the `paypal_checkout_sdk` in the JS file to `paypal` there is a different button that opens an overlay at least. I already deleted all caches, removed any other paypal sources and checked there is no other paypal related things in the entire code. Is there a way to make a real redirect to paypal instead of this overlay?

**Comment by nfourtythree** [comment]
Hi @Anubarak 

This gateway does not require a `gatewayPostRedirectTemplate` as it happens in a pop-up window on the page.

You should find removing this setting from your config will get things working.

Thanks!
