### ISSUE TITLE
Manual order creation payment options

### ISSUE THREAD

**Issue by mattsbanner** [craftcms/commerce-paypal-checkout#17]
I can't see a way to use the PayPal Checkout gateway when manually creating an order via the CP. 

The option for payment via this gateway appears, but it doesn't seem to have any functionality and the order cannot be paid for. 

![modal](https://user-images.githubusercontent.com/49304331/83265180-0ac62180-a1b9-11ea-910a-02c7c152211e.png)

![transactions](https://user-images.githubusercontent.com/49304331/83265188-10236c00-a1b9-11ea-99be-c93d3ab12adc.png)

Ideally, it would be possible to enter a users card details via the Debit / Credit card option shown on the front-end. However, if this isn't possible, it feels like this gateway should be hidden from manual transactions within the CP.

Thanks.

**Comment by nfourtythree** [comment]
Hi @mattsbanner 

Currently, the Commerce PayPal Checkout plugin is designed to use the PayPal Checkout integration which is designed around a customer purchase experience/checkout flow.

For taking payments with PayPal over the phone or other card-not-present situations you would need to look into PayPal's virtual terminal https://www.paypal.com/merchantapps/appcenter/acceptpayments/virtualterminal

I agree, that if the functionality is not available for this gateway we should not be showing it in the list, I have created an issue for that and will get it fixed https://github.com/craftcms/commerce-paypal-checkout/issues/30

Thanks for the issue/feedback!
