### ISSUE TITLE
"Expected an order id to be passed" error.... using demo 'shop' templates

### ISSUE THREAD

**Issue by j-greig** [craftcms/commerce-paypal-checkout#19]
Am getting the "Expected an order id to be passed" error in my local dev environment (Valet)....

* Using project config
* Using sandbox creds via .env
* Using the demo "/shop" templates (was initially testing using a customer checkout template and got the same error)
* Settings: test mode is on
* Settings: "Should commerce send cart information to gateway" is on
* Cart contents: 2 normal products, no sales or discounts etc
* Checkout user: logged in with a previously registered account

What might I have missed?

```
    "aelvan/imager": "v2.4.0",
    "aelvan/mailchimp-subscribe": "3.0.2",
    "am-impact/amcommand": "3.1.4",
    "anubarak/craft-relabel": "1.3.5.2",
    "craftcms/cms": "3.4.24",
    "craftcms/commerce": "3.1.9",
    "craftcms/commerce-paypal": "2.1.0.1",
    "craftcms/commerce-paypal-checkout": "1.1.0",
    "craftcms/commerce-stripe": "2.3.1.1",
    "craftcms/feed-me": "4.2.3",
    "craftcms/mailgun": "1.4.3",
    "craftcms/redactor": "2.6.1",
    "doublesecretagency/craft-cpcss": "2.2.1",
    "doublesecretagency/craft-matrixcolors": "2.0.1",
    "focuslabllc/craft-cheat-sheet": "2.0.3",
    "kinoli/groupie": "1.0.3",
    "marionnewlevant/snitch": "3.0.1",
    "mmikkel/cp-clearcache": "1.0.6",
    "mmikkel/cp-field-inspect": "1.1.3",
    "nav33d/craft-relations": "1.2.1",
    "nystudio107/craft-scripts": "^1.2",
    "nystudio107/craft-seomatic": "3.3.8",
    "olivierbon/craft-concierge": "dev-master",
    "putyourlightson/craft-snaptcha": "2.2.5",
    "superbig/craft-entry-instructions": "1.0.7",
    "verbb/cloner": "1.1.2",
    "verbb/cp-nav": "3.0.12",
    "verbb/image-resizer": "2.0.9",
    "verbb/knock-knock": "1.2.9.1",
    "verbb/super-table": "2.5.1",
    "vlucas/phpdotenv": "^2.4.0"
```

Update: log for my payment attempts locally, lots of gateway errors before it finally worked.
![image](https://user-images.githubusercontent.com/616194/85266499-d5d18580-b46b-11ea-832a-6d54fdc5150d.png)

**Comment by j-greig** [comment]
So weird, as soon as I'd posted this it somehow started working — just wish I knew why :) 

Perhaps the docs would benefit from a checklist to help people avoid this issue as it seems quite common.

**Comment by nfourtythree** [comment]
Hi @j-greig 

It would be great if you could provide fulls details on that would reproduce this error. This would include things like product names, taxes applied, shipping methods, billing and shipping addresses.

Unfortunately, I am unable to replicate the issue. This usually means that it comes down to something out of these three things:

1) PayPal account
2) Data on the order
3) Custom code

As noted in your screenshot you have a "service error" response from PayPal there is also a debug ID that you can use when contacting PayPal customer support for them to be able to look into the logs. To me, that error sounds like a 500 error on the PayPal sandbox (which unfortunately is not uncommon) this would explain why it started working again.

**Comment by j-greig** [comment]
Thanks @nfourtythree, if I get some downtime I'll try and replicate on a vanilla install of Craft too. Will let you know either way though :  )

**Comment by j-greig** [comment]
1. Can confirm that the demo /shop templates work fine locally and the PayPal popup opens, and can complete the purchase.

2. I've also noticed that if I trigger the PayPal popup via our custom template shortly after testing (1.), the order ID error doesn't happen and the PayPal popup/pamment magically works. (Not sure what this means though, it's like the session carries over or something... ? 🤷‍♂️)

**Comment by nfourtythree** [comment]
Hi @j-greig 

Glad you have got this working. To me, as I mentioned before, it seems like this was an intermittent issue with PayPal sandbox. Which, from my previous experience, is not uncommon.

Will close the issue for now, but please post an update if you find a way of consistently replicating the issue.

Thanks!

**Comment by j-greig** [comment]
What data order could affect this?

I have just copied the form button and JS function from the plugin code verbatim into my template and still getting the missing order ID error locally most of the time. 

Driving me a bit nuts now!

**Comment by j-greig** [comment]
One thing I've just noticed — sometimes the missing order ID error even happens when using your /shop demo templates. Not all of the time though...

![image](https://user-images.githubusercontent.com/616194/85729258-8ea7f680-b6f0-11ea-82c8-c59b3de7dfbc.png)

**Comment by nfourtythree** [comment]
Hi @j-greig 

Any data in the order, items, addresses, adjusters etc. Without knowing what is causing it, it is difficult to say.

Also with the fact that it is intermittent, it would likely mean it is a PayPal thing (if you are using the same data).

As I mentioned before to be able to help we need a reliable way of reproducing the error. That would mean providing all the steps along the way. What products were used, how many were added to the cart, in what order, what addresses were using, were both addresses supplied, gateway settings, Paypal account settings etc.

As you can see there is a lot of information that could be at play here, so we really need a concrete way of producing the error to give us a chance to hunt it down and fix it.

Here are some comments by a PayPal dev on another issue that encourage people to get the debug ID and contact PayPal customer support: [comment 1](https://github.com/paypal/paypal-checkout-components/issues/1224#issuecomment-613119855), [comment 2](https://github.com/paypal/paypal-checkout-components/issues/1224#issuecomment-616252743) and [comment 3 (explains how to get the debug id)](https://github.com/paypal/paypal-checkout-components/issues/1224#issuecomment-616894772)

Thanks.

**Comment by j-greig** [comment]
Steps to reproduce:

1. Default install of Craft + Commerce
2. Add "1 x A New Toga" to cart
2. Checkout via demo templates eg `shop/checkout` in Incognito tab
3. Make sure you are NOT logged in as a user
4. Complete Guest checkout sequence, shipping to James Greig James Greig Flat 0/1, 81 White Street G11 5DD Glasgow United Kingdom 07817284568
4. Get the missing order ID error (see below)

Currency: GBP
PayPal settings: (see below)

![image](https://user-images.githubusercontent.com/616194/85737409-45a77080-b6f7-11ea-944d-d52e5be8d96d.png)

![image](https://user-images.githubusercontent.com/616194/85736989-e34e7000-b6f6-11ea-94a6-951b4016aa62.png)

**Comment by j-greig** [comment]
Thanks for clarifying @nfourtythree !

I can't follow those steps to get the debug ID as the PayPal checkout popup window doesn't stay open.

Will revert to the old Paypal gateway for now I think : (

**Comment by nfourtythree** [comment]
@j-greig to get the debug ID you only need to look for the call to the Paypal `/graphql` endpoint in your network tab of dev tools.

You can also see it in the first screenshot that you posted:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/E0uzKooG/Image%202020-06-26%20at%208.26.50%20am.png?v=a4ce399a9197b492fb1b43b4e6b3922d)
