### ISSUE TITLE
'Test mode?' lightswitch on settings page should report if being overridden by environment config

### ISSUE THREAD

**Issue by j-greig** [craftcms/commerce-paypal-checkout#22]
### Description
When viewing the PayPal Checkout gateway settings, it's not clear* if 'Test mode' is being overridden by [a gateway configuration](https://docs.craftcms.com/commerce/v3/gateway-config.html). Could the settings tell you if this is the case, similar to other settings pages elsewhere in Craft?

(Update: just realised that the `PAYPAL_TEST_MODE` env only works if set to a "0""1" value rather than "true"/"false". It would be good if this was mentioned in the docs).

![image](https://user-images.githubusercontent.com/616194/88018884-7c1eb280-cb20-11ea-8cab-a0beecb89392.png)

**Comment by orosznyet** [comment]
This is also misleading while using project config, not to mention one accidental save and the value gets overwritten.

**Comment by pdaleramirez** [comment]
The bug here is that the testMode setting only accepts `0` and `1` values where it should also accept boolean `true` and `false` values.

**Comment by nfourtythree** [comment]
This is now the case after the latest Craft update which provided support for environment variables in boolean fields.

![Screenshot 2021-12-13 at 09 19 19](https://user-images.githubusercontent.com/266453/145785060-ea86e8c0-21f3-4d2e-a3af-fc057d5c4f4b.png)
