### ISSUE TITLE
Expected an order id to be passed

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce-paypal-checkout#3]
Hello,

I created a fresh installation and copied over the shop templates from vendor to the app's templates directory.  I tried to complete payment but got the error:

```Expected an order id to be passed```

![image](https://user-images.githubusercontent.com/744385/68511819-9b441100-022b-11ea-8c76-8a28b3053f73.png)

Thanks

**Comment by nfourtythree** [comment]
Were their any JS errors in the console?

Or any errors in the logs?

**Comment by keyurshah** [comment]
Got it sorted out, I had to enable test mode.
