### ISSUE TITLE
📝 PayPal Live return URL?

### ISSUE THREAD

**Issue by billmn** [craftcms/commerce-paypal-checkout#34]
**Description**
I'm creating a Live API credentials in PayPal Developer portal. With the "Connect with PayPal" option checked, Paypal returns me this message:

![image](https://user-images.githubusercontent.com/779534/116614484-483bad80-a93a-11eb-9170-0f24bd79db87.png)

I haven't found in the README any information about that. 

What should I enter in this field?

Should we update the README to clarify this situation?

Thank you

**Comment by nfourtythree** [comment]
Hi @billmn 

The implementation of this gateway will allow users to login to PayPal to pay for their purchase. As far as I am aware you do not need the "Connect with PayPal" box checked. I do not have it checked on my sandbox account and everything works exactly as expected.

You should also be able to click "hide" on the "return URL" and therefore not need to fill it out. All the URLs for the process of talking between the site and PayPal are done at run time in the code.

Hope this helps, thanks!

**Comment by billmn** [comment]
Thank you @nfourtythree for the explanation. 🙏

The README say:
```
Request permissions for REST API features that apply to your integration:
    - PayPal payments
    - Connect with PayPal
```

Do you think could be useful update this part of readme?

**Comment by nfourtythree** [comment]
Hi @billmn 

Great point! I will get the README updated to prevent any confusion in the future.

Thanks!

**Comment by marionnewlevant** [comment]
We had this identical issue. For anyone else who stumbles across this thread, you should also know that in Paypal sandbox mode you need to test with sandbox accouts. Paypal doc :  [ https://developer.paypal.com/developer/accounts/](https://developer.paypal.com/developer/accounts/)
