### ISSUE TITLE
Paypal strings are limited to a certain length

### ISSUE THREAD

**Issue by okolvik-avento** [craftcms/commerce-paypal-checkout#39]
**Description**
The description field (or custom field?) sent to paypal can exceed the paypal api maximum length.

**To Reproduce**
How, and what happened?
1. Have an item with a long description
2. Pay with paypal
3. "error":"{\"name\":\"INVALID_REQUEST\",\"message\":\"Request is not well-formed, syntactically incorrect, or violates schema.\",\"debug_id\":\"d8f478168bac9\",\"details\":[{\"field\":\"/purchase_units/@reference_id=='default'/items/0/name\",\"value\":\"****************************************************************************************************************************************************************\",\"location\":\"body\",\"issue\":\"INVALID_STRING_LENGTH\",\"description\":\"The value of a field is either too short or too long.\"}],\"links\":[{\"href\":\"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_STRING_LENGTH\",\"rel\":\"information_link\",\"encType\":\"application/json\"}]}",

**Expected behavior**
String limited to paypal api maximum

**Additional info**
- Craft version: Craft Pro 3.6.17
- Commerce PayPal Checkout version: 1.2.1
- Commerce version: 3.3.4.1

**Additional context**
Probably affects other data as well?

**Comment by nfourtythree** [comment]
Hi @okolvik-avento 

Thank you for bringing this to our attention. We have pushed a fix that will be included in a patch release of the plugin shortly.

Thanks!
