### ISSUE TITLE
Paypal offers option to change shipping address

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce-paypal-checkout#4]
When i select the top PayPal yellow button, I get the login screen for paypal.

It seems that in Paypal, it lets you change the shipping address. But if you do change it in Paypal, it's not reflected in the Craft Commerce order. This would be confusing for the customer.

It would be preferable for the address not to be changed at all in Paypal. And leave Craft Commerce as the source of truth since shipping has already been calculated based on the original address. Hopefully that is a setting that can be added. 

Original address selected upon payment

![image](https://user-images.githubusercontent.com/744385/68515403-a865fd80-0235-11ea-8cf6-07de8776cbbd.png)

![image](https://user-images.githubusercontent.com/744385/68515002-52dd2100-0234-11ea-9612-04af11b36342.png)

Address options presented in Paypal

![image](https://user-images.githubusercontent.com/744385/68515032-7011ef80-0234-11ea-9531-9f6fc2f6d383.png)

Address changed in Paypal

![image](https://user-images.githubusercontent.com/744385/68515015-5e304c80-0234-11ea-9c8e-97454d6243fc.png)

Final order shows original address.

![image](https://user-images.githubusercontent.com/744385/68515163-d6970d80-0234-11ea-8e65-886baab1bc57.png)

**Comment by nfourtythree** [comment]
In the request we are passing ‘SET_PROVIDED_ADDRESS’ https://github.com/craftcms/commerce-paypal-checkout/blob/1a79b8064aec397a63b72912fa3e00dd63fc273c/src/gateways/Gateway.php#L493

Which according to the [PayPal docs](https://developer.paypal.com/docs/api/orders/v2/#orders_create) should lock down the editing of the shipping address:

> ‘SET_PROVIDED_ADDRESS‘. Use the merchant-provided address. The customer cannot change this address on the PayPal site.

This seems like it could be an issue with the PayPal sandbox.

**Comment by keyurshah** [comment]
I tried updating to live and still got the option to change address.

![image](https://user-images.githubusercontent.com/744385/68617200-9aa1b980-047b-11ea-850d-0b58ab27ada9.png)

i just saw the note about the typo, hopefully that will fix it.

**Comment by nfourtythree** [comment]
Hi @keyurshah, I have pushed a new release that fixes this typo. 

Thanks for the heads up on the issue
