### ISSUE TITLE
Package paypal/paypalhttp is abandoned

### ISSUE THREAD

**Issue by MattWilcox** [craftcms/commerce-paypal-checkout#41]
On install a warning is thrown in composer's output:

`Package paypal/paypalhttp is abandoned, you should avoid using it. No replacement was suggested.`

Not promising when it's an ecommerce thing dealing with money - is this actually an issue?

**Comment by fantasticmachine** [comment]
@MattWilcox I installed this yesterday (10th Jan) and didn't see that warning.

Just installed it on another site to double check and no warning raised. Do you have the other Paypal gateway installed too? That's the one which is deprecated.

**Comment by nfourtythree** [comment]
Hi @MattWilcox 

As @fantasticmachine mentioned, I am unable to replicate what you are seeing.

Are you able to provide steps to reproduce this issue?

Thanks!

**Comment by MattWilcox** [comment]
Hey guys, sorry this is from 5months ago - no idea anymore what project this was on, or why it's popped up for you now!

**Comment by nfourtythree** [comment]
Thanks for the update @MattWilcox 

Will close this for now, please update the issue if you notice any problems in the future and I can reopen and investigate.

Thanks!
