### ISSUE TITLE
Currency Error

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce-paypal-checkout#45]
**Description**
I am trying to pass `USD` as the currency to the `getPaymentFormHtml` tag but the following error keeps showing up when I click the PayPal button. 

```
Error: Expected currency from order api call to be USD, got EUR. Please ensure you are passing currency=EUR to the sdk url. https://developer.paypal.com/docs/checkout/reference/customize-sdk/
```

Using the currency `EUR` works fine, but I need to show the prices as `USD` in PayPals popup window. 

Is this because the Base currency in Commerce is set to `EUR`? I would have thought that you can just pass any of the PayPal supported currencies to this option and it would work fine?!

**Comment by nfourtythree** [comment]
Hi @iamtompickering 

Thank you for your message.

As well as passing `USD` to customise the PayPal SDK are you also setting the payment currency on the order? ([see points 2 or 3](https://craftcms.com/docs/commerce/3.x/payment-currencies.html#switching-currencies))

Thanks.

**Comment by iamtompickering** [comment]
@nfourtythree ahhh yes looks like that was still being returned as `EUR`. 

I've reworked my forms now to update the `paymentCurrency` and all appears to be working, thanks! 👌

**Comment by nfourtythree** [comment]
Hi @iamtompickering 

Glad everything is working now!

Thanks.
