### ISSUE TITLE
Gateway redirects to "paypal result id" when trying to pay

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce-paypal-checkout#61]
**Description**
Gateway redirects to "paypal result id" when trying to pay

**To Reproduce**
How, and what happened?
1. When selecting this gateway and then submitting to `commerce/payments/pay`, I get redirected to just the paypal result id.

**Expected behavior**
I expect to be redirected to Paypal 

**Additional info**
- Craft version: 4
- Commerce PayPal Checkout version: 2
- Commerce version: 4
- PHP version: 8.1
- Database driver & version: PostgreSQL
- Other Plugins & versions: -

**Additional context**
Looking in the source code of this plugin I see that this line might be responsible: https://github.com/craftcms/commerce-paypal-checkout/blob/develop/src/responses/CheckoutResponse.php#L146

**Comment by vandres** [comment]
@boboldehampsink How did you solve it? I am having big troubles getting the PayPal-integration to work

**Comment by boboldehampsink** [comment]
You have the implemented the payment form. It has no direct offsite handler.

**Comment by boboldehampsink** [comment]
Sure
