### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by tom-c** [craftcms/commerce-paypal-checkout#7]
It seems that env vars aren't not working with this gateway, if used the client_id isn't passed to the script src, and additionally payments attempts result in 'missing order id'.  Not a massive problem but the gateway settings include the 'can be set as an environment variable' so it tripped me up for a while.

**Comment by nfourtythree** [comment]
Hi @tom-c 

Thanks for the heads up, have fixed the issue with environment variables with `clientId` and `secret` here: 8311e096a771ddde02f0d020504362beca2729e2. This will be included in the next release

You mentioned something about "missing order ID" are you able to expand on this? Is there a way to replicate the issue?

Thanks!

**Comment by tom-c** [comment]
That was quick :)

The 'missing order id' is the error the PayPal SDK spits out as an alert if you try to checkout while the plugin is using env vars. Tracked it down via js debug in the inspector and it was the call to 'commerce/payments/pay' returning unauthorised. That's what led me to discover the env vars weren't working… In your code it's the data.transactionId.

Am using my own paymentForm twig and JS which is also what led me to discover this after pulling some hair out last night.

Thank you

**Comment by nfourtythree** [comment]
Ah ok so was related to the ENV issue.

I will close this issue and get a release out for the plugin.

Thanks!
