### ISSUE TITLE
PayPal error: Shipping city required 

### ISSUE THREAD

**Issue by joostwaaijer** [craftcms/commerce-paypal-checkout#76]
**Description**
Paypal checkout is returning the following error when trying to buy from United Arab Emirates:

```
{
	"name": "UNPROCESSABLE_ENTITY",
	"details": [{
		"field": "/purchase_units/@reference_id=='default'/shipping/address/admin_area_2",
		"issue": "CITY_REQUIRED",
		"description": "The specified country requires a city (address.admin_area_2)"
	}],
	"message": "The requested action could not be performed, semantically incorrect, or failed business validation.",
	"debug_id": "c41446ace65eb",
	"links": [{
		"href": "https://developer.paypal.com/docs/api/orders/v2/#error-CITY_REQUIRED",
		"rel": "information_link",
		"method": "GET"
	}]
}
```

The city is saved in the craft commerce systems as locality, but when checking the address forms for the United Arab Emirates, there is no possible way to set the locality, see image:
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/6860529/232693195-23077cb0-914a-4d75-8cf3-88fc960e1083.png">

**To Reproduce**
How, and what happened?
1. Add items to cart
2. Add billing and shipping address info from United Arab Emirates
3. Go to checkout
4. Receive the error

**Expected behavior**
Orders from United Arab Emirates should be able to checkout.

**Additional info**
- Craft version: 4.4.7
- Commerce PayPal Checkout version: 2.1.2
- Commerce version: 4.2.7
- PHP version: 8.2.3
- Database driver & version: PostgreSQL 12.14

**Comment by lukeholder** [comment]
You are correct that the "Locality" field is not defined as a "used field" by our Google-supplied address data for the United Arab Emirates, but it looks like Paypal requires it.

To manually add it to the "used fields" data for that Country, please add the following to your project inside a module:


```php
Event::on(
    \craft\services\Addresses::class,
    \craft\services\Addresses::EVENT_DEFINE_USED_FIELDS,
    function (\craft\events\DefineAddressFieldsEvent $event) {
        if($event->countryCode == 'AE'){
            $fields = array_merge(['locality'],$event->fields);
            $event->fields = $fields;
        }
    }
);
```

This will allow the field to be added to addresses for that country in the CP and the front-end.

Hope that helps.

**Comment by ryssbowh** [comment]
If I may reopen this, we have existing addresses for those countries without city and asking users to amend their addresses to add a city for a country that doesn't have one sounds a bit silly.

Can this plugin not check that the address doesn't have a locality and add the the country as locality on the paypal payload ?

I've fixed this by manually adding the country to the address through an event :
```
Event::on(Elements::class, Elements::EVENT_BEFORE_SAVE_ELEMENT, function ($event) {
    $address = $event->element;
    if (ElementHelper::isDraftOrRevision($address) or !($address instanceof Address)) {
        return;
    }
    if ($address->owner instanceof Order and !$address->locality and $address->countryCode) {
        $address->locality = $address->country->getName();
    }
});
```
But it sounds a bit dirty, can the paypal payload be modified through an event ?
