### ISSUE TITLE
"Can not refund amount greater than the remaining amount" when the entered amount is the remaining amount

### ISSUE THREAD

**Issue by jakelapan** [craftcms/commerce-paypal-checkout#81]
**Description**
A customer paid using paypal gateway. The customer requested a partial refund which succeeded. Then the customer requested a full refund. When using the "Refund" button with a provided amount (which was the remaining balance that the customer paid), we received the following error: **Can not refund amount greater than the remaining amount**

The balance was correct, but what is interesting is I was able to find a work around by NOT entering in an amount and clicking the refund button, thus allowing the default value to be submitted (which was the same as the amount that I manually entered) and that was able to be successfully refunded.

**To Reproduce**
How, and what happened?
1. Place an order with paypal checkout
2. Complete a partial refund
3. Try to submit another refund for the balance by manually entering in the amount in the field (error thrown)
4. Try NOT entering in an amount in the field and hut refund (success)

**Expected behavior**
I expect the entered in value to be refunded if the balance is equal to the amount entered when trying to refund the order in full after a successful partial refund.

**Additional info**
- Craft version: Craft Pro 4.4.15
- Commerce PayPal Checkout version: 2.1.2
- Commerce version: 4.2.11
- PHP version: 8.2.8
- Database driver & version: MySQL 8.0.34

**Comment by nfourtythree** [comment]
Hi @jakelapan 

Thank you for your report. Unfortunately, I am unable to replicate this issue.

Do you remember if this was for an order that was paid for in a currency different to the base currency?

Thanks!

**Comment by nfourtythree** [comment]
Closing this issue as it has become stale, if you have any further information please update this issue and we can re-open and look into it.

Thanks!
