### ISSUE TITLE
Remove reference to polyfill.io please

### ISSUE THREAD

**Issue by elibosley** [craftcms/commerce-paypal-checkout#87]
This domain is now hijacked and is distributing malware. 

https://github.com/craftcms/commerce-paypal-checkout/blob/d352dcb816ca95ac6bb51a167b2ec1ed5f1e7469/src/gateways/Gateway.php#L355

**Comment by lukeholder** [comment]
We have gone ahead and made the CDN fix to the Paypal Checkout plugin for all major versions. The fixed versions are 1.3.5, 2.1.3, and 3.0.1.

**Comment by zackspear** [comment]
Thanks for the quick turnaround.
