### ISSUE TITLE
Partial Payment Bug

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce-paypal-checkout#9]
Experiencing an issue where the total order value is being passed to PayPal rather than the outstanding amount, where an order has been partially paid or an additional charge has been added `{{ order.getOutstandingAmount() }}` returns the correct amount to pay, but passes and processes the total order value in PayPal.

**Comment by samhibberd** [comment]
Awesome. Thanks @nfourtythree

**Comment by nfourtythree** [comment]
@samhibberd release has been pushed so you are free to update! 👍
